// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: macro.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from macro.proto</summary>
public static partial class MacroReflection {

  #region Descriptor
  /// <summary>File descriptor for macro.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MacroReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgttYWNyby5wcm90bypgCgxTZXJ2ZXJTdGF0dXMSBwoDZml4EAASBwoDaG90",
          "EAESCAoEb3BlbhACEggKBGdvb2QQAxIJCgVjbG9zZRAEEggKBGJ1c3kQBRIV",
          "ChFjbG9zZVRlYW1BbmRMb2dpbhAGKiYKC0dhbWVyU3RhdHVzEgsKB29mZmxp",
          "bmUQABIKCgZvbmxpbmUQASqrBQoLR01FdmVudFR5cGUSCwoHTm90aGluZxAA",
          "EgwKCFJlY2hhcmdlEAESDQoJQWRkcGxheWVyEAISEAoMVXBkYXRlUGxheWVy",
          "EAMSEwoPVXBkYXRlR2FtZXJNYWluEAQSFQoRVXBkYXRlR2FtZXJOdW1iZXIQ",
          "BRIVChFVcGRhdGVHYW1lclNlYXNvbhAGEg0KCURlbFBsYXllchAHEhEKDURl",
          "bEl0ZW1JblBhY2sQCBIRCg1BZGRHb2RQbGF5ZXJzEAkSDAoIR2FtZXJCYW4Q",
          "ChIPCgtHYW1lclNpbGVudBALEhAKDERlbEdhbWVyTWFpbBAMEhEKDURlbEdh",
          "bWVyR29vZHMQDRIVChFVcGRhdGVHYW1lclN0YXRpYxAOEhEKDURlbFBsYXll",
          "clNraW4QDxIZChVVbmxvY2tQbGF5ZXJTa2lsbFJ1bmUQEBIaChZVcGRhdGVH",
          "YW1lckdvb2RzTnVtYmVyEBESGAoURmluaXNoR2FtZXJEYWlseVRhc2sQEhIS",
          "Cg5GaW5pc2hHYW1lclBWRRATEg0KCURlbEZyaWVuZBAUEhQKEE9uZUtleUVx",
          "dWlwU2tpbGwQFRIRCg1QbGF5ZXJNYXJrTWF4EBYSFQoRVXBkYXRlR2FtZXJB",
          "dmF0YXIQFxIWChJVcGRhdGVHYW1lclRpbWVSZWMQGBIaChZSZXNldEdhbWVy",
          "U2hvcEZyZXNoVG1zEBkSFgoSVXBkYXRlR2FtZXJUYXNrUmVjEBoSEQoNSW5j",
          "ckZyaWVuZFFtZBAbEhEKDURlbEJsYWNrR2FtZXIQHBIUChBVUGRhdGVHYW1l",
          "clRpdGxlEB0SEgoOVXBsb2FkR2FtZXJMb2cQHhIUChBEZWxHYW1lckxCU1Rp",
          "dGFsEB8SFAoQU2V0R2FtZXJMQlNTY29yZRAgKikKCU1haWxTdGF0ZRIOCgpN",
          "YWlsVW5SZWFkEAASDAoITWFpbFJlYWQQASptCghNYWlsVHlwZRIQCgxBY3Rp",
          "dml0eU1haWwQABILCgdTeXNNYWlsEAESFAoQQW5ub3VuY2VtZW50TWFpbBAC",
          "Eg0KCUhlbGxvTWFpbBADEg4KClJlY2FsbE1haWwQBBINCglHYW1lck1haWwQ",
          "BSozChNNYWlsQXR0YWNobWVudFN0YXRlEg4KClVuUmVjZWl2ZWQQABIMCghS",
          "ZWNlaXZlZBABKlQKC0NoYXRNc2dUeXBlEg0KCU1zZ0ZyaWVuZBAAEg4KCk1z",
          "Z1RydW1wZXQQARIKCgZNc2dTeXMQAhINCglNc2dQdWJsaWMQAxILCgdNc2dH",
          "aWZ0EAQqHgoKU0RLQ2hhbm5lbBIGCgJHTRAAEggKBE1pbmUQASpOCglTZXJ2",
          "ZXJUYWcSDwoLU2VydmVyTm9UYWcQABINCglTZXJ2ZXJOZXcQARIPCgtTZXJ2",
          "ZXJSZWNvbRACEhAKDFNlcnZlckhpZGRlbhADKj0KEU1lc3NhZ2VUYXJnZXRU",
          "eXBlEgsKB01UVF9BbGwQABIMCghNVFRfU2VsZhABEg0KCU1UVF9Hcm91cBAC",
          "KtYBCgxMQlNRdWFyeVR5cGUSDAoITFFUX05PTkUQABIOCgpMUVRfTkFUSU9O",
          "EAESEgoOTFFUX0xPQ0FUSU9OX0EQAhISCg5MUVRfTE9DQVRJT05fQhADEhIK",
          "DkxRVF9MT0NBVElPTl9DEAQSFQoRTFFUX0xPQ0FUSU9OX0FSRUEQBRIXChNM",
          "UVRfTE9DQVRJT05fRlJJRU5EEAYSFAoQTFFUX0xPQ0FUSU9OX0xCUxAHEhMK",
          "D0xRVF9MT0NLX05BVElPThAIEhEKDUxRVF9OQVRJT05fRVgQCSpGCgtDaGFu",
          "bmVsVHlwZRIOCgpDSEFOTkVMX1BDEAASFAoQQ0hBTk5FTF9MQ01fQV9DThAB",
          "EhEKDUNIQU5ORUxfQVBQTEUQAipCCg5DaGFubmVsQWxsVHlwZRIaChZDSEFO",
          "TkVMX0FMTF9JT1NBTkRST0lEEAASFAoQQ0hBTk5FTF9BTExfTUFJThABKukB",
          "ChBTZXJ2ZXJPbmxpbmVUeXBlEg4KClNlcnZlcl9PQlQQABIRCg1TZXJ2ZXJf",
          "T0JUX1FBEAESFQoRU2VydmVyX0lPU19WRVJJRlkQAhIZChVTZXJ2ZXJfQU5E",
          "Uk9JRF9WRVJJRlkQAxIRCg1TZXJ2ZXJfUzFfQVZBEAQSEAoMU2VydmVyX1Mx",
          "X1FBEAUSGAoUU2VydmVyX1MxX0lPU19WRVJJRlkQBhIcChhTZXJ2ZXJfUzFf",
          "QU5EUk9JRF9WRVJJRlkQBxIQCgxTZXJ2ZXJfREFJTFkQCBIRCg1TRVJWRVJf",
          "V0VFS0xZEAkq5gEKBlRhc2tJZBIQCgxUYXNrX0lEX05vbmUQABIWChJUYXNr",
          "X0lEX0RhaWx5X1Rhc2sQARIVChFUYXNrX0lEX01haW5fVGFzaxACEhcKE1Rh",
          "c2tfSURfU3RyZWV0X1Rhc2sQAxIbChdUYXNrX0lEX0ludml0YXRpb25fVGFz",
          "axAEEhcKE1Rhc2tfSURfV2Vla2x5X1Rhc2sQBRIWChJUYXNrX0lEX1RocmVl",
          "X1Rhc2sQBhIXChNUYXNrX0lEX0FjdGl2ZV9UYXNrEAcSGwoXVGFza19JRF9T",
          "ZXZlbl9EYXlzX1Rhc2sQCCo9CgtPcmRlclN0YXR1cxIJCgVCZWdpbhAAEgoK",
          "Bk5vdGlmeRABEgoKBkZpbmlzaBACEgsKB1B1Ymxpc2gQAyqLBQoKUmVkcG9p",
          "bnRJRBILCgdudWxsUmVkEAASDAoIbWFpblRhc2sQZRINCglkYWlseVRhc2sQ",
          "ZhITCg90aHJlZU1hc3RlclRhc2sQZxIRCg1zZXZlbkRheXNUYXNrEGgSDQoI",
          "Z29sZFNob3AQyQESEAoLZGlhbW9uZFNob3AQygESDwoKcGFja2V0U2hvcBDL",
          "ARIRCgxyZWNoYXJnZVNob3AQzAESEwoOcmVwdXRhdGlvblJhbmsQrQISDwoK",
          "bWF0Y2hpbmdsdhCRAxINCghza2lsbE5ldxD1AxIRCgxza2lsbExldmVsdXAQ",
          "9gMSEgoNc2tpbGxFcXVpcFBvcxD3AxIVChBlcXVpcG1lbnRCb3hGcmVlENkE",
          "EhcKEmVxdWlwbWVudEJveEZyZWVBZBDaBBIYChNlcXVpcG1lbnRCb3hMZXZl",
          "bHVwENsEEhgKE2VxdWlwbWVudEJveFRlbkRyYXcQ3AQSCQoEbWFpbBC9BRIO",
          "CgllcXVpcG1lbnQQoQYSFAoPZGV0YWxEdWVJdGVtTWF4EIUHEhMKDmRldGFs",
          "RHVlUmV3YXJkEIYHEhEKDHNraWxsQm94RnJlZRDpBxITCg5za2lsbEJveEZy",
          "ZWVBZBDqBxIUCg9za2lsbEJveFRlbkRyYXcQ6wcSFgoRdGhyZWVNYXN0ZXJT",
          "ZWFzb24QzQgSGwoWY2xpbWJpbmdUb3dlck5vcm1Td2VlcBCxCRIZChRjbGlt",
          "YmluZ1Rvd2VyQURTd2VlcBCyCRIfChpyZWNoYXJnZVZpcENhcmREYWlseVJl",
          "d2FyZBCVChIWChFuZXdiaWVTaWduSW5Bd2FyZBD5ChIZChRzZXZlbkRheXNT",
          "aWduSW5Bd2FyZBD6CkIGWgQuL3BiYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ServerStatus), typeof(global::GamerStatus), typeof(global::GMEventType), typeof(global::MailState), typeof(global::MailType), typeof(global::MailAttachmentState), typeof(global::ChatMsgType), typeof(global::SDKChannel), typeof(global::ServerTag), typeof(global::MessageTargetType), typeof(global::LBSQuaryType), typeof(global::ChannelType), typeof(global::ChannelAllType), typeof(global::ServerOnlineType), typeof(global::TaskId), typeof(global::OrderStatus), typeof(global::RedpointID), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
///区服状态
/// </summary>
public enum ServerStatus {
  /// <summary>
  ///维护中
  /// </summary>
  [pbr::OriginalName("fix")] Fix = 0,
  /// <summary>
  ///火爆
  /// </summary>
  [pbr::OriginalName("hot")] Hot = 1,
  /// <summary>
  ///开放
  /// </summary>
  [pbr::OriginalName("open")] Open = 2,
  /// <summary>
  ///流畅
  /// </summary>
  [pbr::OriginalName("good")] Good = 3,
  /// <summary>
  ///关闭中
  /// </summary>
  [pbr::OriginalName("close")] Close = 4,
  /// <summary>
  ///繁忙
  /// </summary>
  [pbr::OriginalName("busy")] Busy = 5,
  /// <summary>
  ///服务器使用,关闭组队和登录,此状态下的区服,玩家可以在大厅玩但是不能登录和组队
  /// </summary>
  [pbr::OriginalName("closeTeamAndLogin")] CloseTeamAndLogin = 6,
}

/// <summary>
///玩家状态
/// </summary>
public enum GamerStatus {
  /// <summary>
  ///离线
  /// </summary>
  [pbr::OriginalName("offline")] Offline = 0,
  /// <summary>
  ///在线
  /// </summary>
  [pbr::OriginalName("online")] Online = 1,
}

/// <summary>
///gm事件类型定义
/// </summary>
public enum GMEventType {
  /// <summary>
  ///占位
  /// </summary>
  [pbr::OriginalName("Nothing")] Nothing = 0,
  /// <summary>
  /// 充值
  /// </summary>
  [pbr::OriginalName("Recharge")] Recharge = 1,
  /// <summary>
  /// 添加球员
  /// </summary>
  [pbr::OriginalName("Addplayer")] Addplayer = 2,
  /// <summary>
  /// 更新球员
  /// </summary>
  [pbr::OriginalName("UpdatePlayer")] UpdatePlayer = 3,
  /// <summary>
  /// 更新玩家信息
  /// </summary>
  [pbr::OriginalName("UpdateGamerMain")] UpdateGamerMain = 4,
  /// <summary>
  /// 更新玩家numberReco信息
  /// </summary>
  [pbr::OriginalName("UpdateGamerNumber")] UpdateGamerNumber = 5,
  /// <summary>
  /// 修改玩家赛季数据
  /// </summary>
  [pbr::OriginalName("UpdateGamerSeason")] UpdateGamerSeason = 6,
  /// <summary>
  /// 删除球员
  /// </summary>
  [pbr::OriginalName("DelPlayer")] DelPlayer = 7,
  /// <summary>
  /// 删除背包道具
  /// </summary>
  [pbr::OriginalName("DelItemInPack")] DelItemInPack = 8,
  /// <summary>
  /// 一键成神
  /// </summary>
  [pbr::OriginalName("AddGodPlayers")] AddGodPlayers = 9,
  /// <summary>
  /// 封停玩家
  /// </summary>
  [pbr::OriginalName("GamerBan")] GamerBan = 10,
  /// <summary>
  /// 禁言玩家
  /// </summary>
  [pbr::OriginalName("GamerSilent")] GamerSilent = 11,
  /// <summary>
  /// 删除玩家邮件
  /// </summary>
  [pbr::OriginalName("DelGamerMail")] DelGamerMail = 12,
  /// <summary>
  /// 删除玩家道具
  /// </summary>
  [pbr::OriginalName("DelGamerGoods")] DelGamerGoods = 13,
  /// <summary>
  /// 修改玩家总统计数据
  /// </summary>
  [pbr::OriginalName("UpdateGamerStatic")] UpdateGamerStatic = 14,
  /// <summary>
  /// 删除皮肤
  /// </summary>
  [pbr::OriginalName("DelPlayerSkin")] DelPlayerSkin = 15,
  /// <summary>
  /// 解锁技能符文
  /// </summary>
  [pbr::OriginalName("UnlockPlayerSkillRune")] UnlockPlayerSkillRune = 16,
  /// <summary>
  /// 修改玩家道具数量
  /// </summary>
  [pbr::OriginalName("UpdateGamerGoodsNumber")] UpdateGamerGoodsNumber = 17,
  /// <summary>
  /// 一键完成每日任务
  /// </summary>
  [pbr::OriginalName("FinishGamerDailyTask")] FinishGamerDailyTask = 18,
  /// <summary>
  /// 一键完成PVE
  /// </summary>
  [pbr::OriginalName("FinishGamerPVE")] FinishGamerPve = 19,
  /// <summary>
  /// 删除好友
  /// </summary>
  [pbr::OriginalName("DelFriend")] DelFriend = 20,
  /// <summary>
  /// 一键安装技能
  /// </summary>
  [pbr::OriginalName("OneKeyEquipSkill")] OneKeyEquipSkill = 21,
  /// <summary>
  /// 一键天赋满级
  /// </summary>
  [pbr::OriginalName("PlayerMarkMax")] PlayerMarkMax = 22,
  /// <summary>
  /// 更新玩家头像/头像框信息
  /// </summary>
  [pbr::OriginalName("UpdateGamerAvatar")] UpdateGamerAvatar = 23,
  /// <summary>
  /// 更新玩家时间数据
  /// </summary>
  [pbr::OriginalName("UpdateGamerTimeRec")] UpdateGamerTimeRec = 24,
  /// <summary>
  /// 重置商品刷新限制
  /// </summary>
  [pbr::OriginalName("ResetGamerShopFreshTms")] ResetGamerShopFreshTms = 25,
  /// <summary>
  /// 更新玩家任务记录数据
  /// </summary>
  [pbr::OriginalName("UpdateGamerTaskRec")] UpdateGamerTaskRec = 26,
  /// <summary>
  /// 增加好友亲密度
  /// </summary>
  [pbr::OriginalName("IncrFriendQmd")] IncrFriendQmd = 27,
  /// <summary>
  /// 删除黑名单好友
  /// </summary>
  [pbr::OriginalName("DelBlackGamer")] DelBlackGamer = 28,
  /// <summary>
  /// 更新玩家头衔
  /// </summary>
  [pbr::OriginalName("UPdateGamerTitle")] UpdateGamerTitle = 29,
  /// <summary>
  /// 上传玩家log
  /// </summary>
  [pbr::OriginalName("UploadGamerLog")] UploadGamerLog = 30,
  /// <summary>
  /// 删除玩家的球员Lbs信息
  /// </summary>
  [pbr::OriginalName("DelGamerLBSTital")] DelGamerLbstital = 31,
  /// <summary>
  /// 设置玩家的球员Lbs积分
  /// </summary>
  [pbr::OriginalName("SetGamerLBSScore")] SetGamerLbsscore = 32,
}

/// <summary>
///邮件阅读状态
/// </summary>
public enum MailState {
  /// <summary>
  ///未读
  /// </summary>
  [pbr::OriginalName("MailUnRead")] MailUnRead = 0,
  /// <summary>
  ///已读
  /// </summary>
  [pbr::OriginalName("MailRead")] MailRead = 1,
}

/// <summary>
///邮件类型
/// </summary>
public enum MailType {
  /// <summary>
  ///活动邮件
  /// </summary>
  [pbr::OriginalName("ActivityMail")] ActivityMail = 0,
  /// <summary>
  ///系统邮件
  /// </summary>
  [pbr::OriginalName("SysMail")] SysMail = 1,
  /// <summary>
  ///公告邮件
  /// </summary>
  [pbr::OriginalName("AnnouncementMail")] AnnouncementMail = 2,
  /// <summary>
  ///欢迎邮件
  /// </summary>
  [pbr::OriginalName("HelloMail")] HelloMail = 3,
  /// <summary>
  ///撤回邮件
  /// </summary>
  [pbr::OriginalName("RecallMail")] RecallMail = 4,
  /// <summary>
  ///玩家邮件
  /// </summary>
  [pbr::OriginalName("GamerMail")] GamerMail = 5,
}

/// <summary>
///邮件附件状态
/// </summary>
public enum MailAttachmentState {
  /// <summary>
  ///未接收
  /// </summary>
  [pbr::OriginalName("UnReceived")] UnReceived = 0,
  /// <summary>
  ///接收
  /// </summary>
  [pbr::OriginalName("Received")] Received = 1,
}

/// <summary>
///聊天消息类型
/// </summary>
public enum ChatMsgType {
  /// <summary>
  ///好友消息
  /// </summary>
  [pbr::OriginalName("MsgFriend")] MsgFriend = 0,
  /// <summary>
  ///喇叭消息
  /// </summary>
  [pbr::OriginalName("MsgTrumpet")] MsgTrumpet = 1,
  /// <summary>
  ///系统消息
  /// </summary>
  [pbr::OriginalName("MsgSys")] MsgSys = 2,
  /// <summary>
  ///公屏消息
  /// </summary>
  [pbr::OriginalName("MsgPublic")] MsgPublic = 3,
  /// <summary>
  ///送礼消息
  /// </summary>
  [pbr::OriginalName("MsgGift")] MsgGift = 4,
}

public enum SDKChannel {
  /// <summary>
  /// GM
  /// </summary>
  [pbr::OriginalName("GM")] Gm = 0,
  /// <summary>
  /// Mine
  /// </summary>
  [pbr::OriginalName("Mine")] Mine = 1,
}

public enum ServerTag {
  /// <summary>
  /// 没有标签
  /// </summary>
  [pbr::OriginalName("ServerNoTag")] ServerNoTag = 0,
  /// <summary>
  /// 新
  /// </summary>
  [pbr::OriginalName("ServerNew")] ServerNew = 1,
  /// <summary>
  /// 推荐
  /// </summary>
  [pbr::OriginalName("ServerRecom")] ServerRecom = 2,
  /// <summary>
  /// 区服隐藏
  /// </summary>
  [pbr::OriginalName("ServerHidden")] ServerHidden = 3,
}

public enum MessageTargetType {
  /// <summary>
  ///所有人
  /// </summary>
  [pbr::OriginalName("MTT_All")] MttAll = 0,
  /// <summary>
  ///自己
  /// </summary>
  [pbr::OriginalName("MTT_Self")] MttSelf = 1,
  /// <summary>
  ///群组
  /// </summary>
  [pbr::OriginalName("MTT_Group")] MttGroup = 2,
}

/// <summary>
///LSB请求类型
/// </summary>
public enum LBSQuaryType {
  [pbr::OriginalName("LQT_NONE")] LqtNone = 0,
  /// <summary>
  ///全国(前10)
  /// </summary>
  [pbr::OriginalName("LQT_NATION")] LqtNation = 1,
  /// <summary>
  ///一级定位
  /// </summary>
  [pbr::OriginalName("LQT_LOCATION_A")] LqtLocationA = 2,
  /// <summary>
  ///二级定位
  /// </summary>
  [pbr::OriginalName("LQT_LOCATION_B")] LqtLocationB = 3,
  /// <summary>
  ///三级定位
  /// </summary>
  [pbr::OriginalName("LQT_LOCATION_C")] LqtLocationC = 4,
  /// <summary>
  ///游戏区
  /// </summary>
  [pbr::OriginalName("LQT_LOCATION_AREA")] LqtLocationArea = 5,
  /// <summary>
  ///好友
  /// </summary>
  [pbr::OriginalName("LQT_LOCATION_FRIEND")] LqtLocationFriend = 6,
  /// <summary>
  ///战区国服最强
  /// </summary>
  [pbr::OriginalName("LQT_LOCATION_LBS")] LqtLocationLbs = 7,
  /// <summary>
  ///国服锁榜
  /// </summary>
  [pbr::OriginalName("LQT_LOCK_NATION")] LqtLockNation = 8,
  /// <summary>
  ///全国(前100)
  /// </summary>
  [pbr::OriginalName("LQT_NATION_EX")] LqtNationEx = 9,
}

/// <summary>
///子渠道枚举
/// </summary>
public enum ChannelType {
  /// <summary>
  ///pc
  /// </summary>
  [pbr::OriginalName("CHANNEL_PC")] ChannelPc = 0,
  /// <summary>
  ///安卓官网
  /// </summary>
  [pbr::OriginalName("CHANNEL_LCM_A_CN")] ChannelLcmACn = 1,
  /// <summary>
  ///iOS官网
  /// </summary>
  [pbr::OriginalName("CHANNEL_APPLE")] ChannelApple = 2,
}

/// <summary>
///总渠道枚举
/// </summary>
public enum ChannelAllType {
  /// <summary>
  ///苹果及安卓官网渠道
  /// </summary>
  [pbr::OriginalName("CHANNEL_ALL_IOSANDROID")] ChannelAllIosandroid = 0,
  /// <summary>
  ///main渠道
  /// </summary>
  [pbr::OriginalName("CHANNEL_ALL_MAIN")] ChannelAllMain = 1,
}

/// <summary>
///服务器的回调类型
/// </summary>
public enum ServerOnlineType {
  /// <summary>
  ///OBT正式服 http://sd2cn-auth-prod.mobage.cn:5050
  /// </summary>
  [pbr::OriginalName("Server_OBT")] ServerObt = 0,
  /// <summary>
  ///OBT QA测试服 http://115.159.49.227:5050
  /// </summary>
  [pbr::OriginalName("Server_OBT_QA")] ServerObtQa = 1,
  /// <summary>
  ///IOS审核服 http://121.199.75.205:5050
  /// </summary>
  [pbr::OriginalName("Server_IOS_VERIFY")] ServerIosVerify = 2,
  /// <summary>
  ///安卓审核服 http://47.110.13.175:5050
  /// </summary>
  [pbr::OriginalName("Server_ANDROID_VERIFY")] ServerAndroidVerify = 3,
  /// <summary>
  ///S1体验服 http://115.159.194.38:5050
  /// </summary>
  [pbr::OriginalName("Server_S1_AVA")] ServerS1Ava = 4,
  /// <summary>
  ///S1QA测试服 http://115.159.48.71:5050
  /// </summary>
  [pbr::OriginalName("Server_S1_QA")] ServerS1Qa = 5,
  /// <summary>
  ///S1 IOS审核服 http://129.211.136.81:5050
  /// </summary>
  [pbr::OriginalName("Server_S1_IOS_VERIFY")] ServerS1IosVerify = 6,
  /// <summary>
  ///S1 安卓审核服 http://106.54.148.216:5050
  /// </summary>
  [pbr::OriginalName("Server_S1_ANDROID_VERIFY")] ServerS1AndroidVerify = 7,
  /// <summary>
  ///日版本 http://47.98.118.120:5050
  /// </summary>
  [pbr::OriginalName("Server_DAILY")] ServerDaily = 8,
  /// <summary>
  ///周版本 http://47.96.22.165:5050
  /// </summary>
  [pbr::OriginalName("SERVER_WEEKLY")] ServerWeekly = 9,
}

/// <summary>
///大任务Id
/// </summary>
public enum TaskId {
  /// <summary>
  ///无效任务id
  /// </summary>
  [pbr::OriginalName("Task_ID_None")] None = 0,
  /// <summary>
  ///每日任务 
  /// </summary>
  [pbr::OriginalName("Task_ID_Daily_Task")] DailyTask = 1,
  /// <summary>
  /// 主线任务
  /// </summary>
  [pbr::OriginalName("Task_ID_Main_Task")] MainTask = 2,
  /// <summary>
  /// 街头任务
  /// </summary>
  [pbr::OriginalName("Task_ID_Street_Task")] StreetTask = 3,
  /// <summary>
  /// 邀请任务
  /// </summary>
  [pbr::OriginalName("Task_ID_Invitation_Task")] InvitationTask = 4,
  /// <summary>
  /// 周任务
  /// </summary>
  [pbr::OriginalName("Task_ID_Weekly_Task")] WeeklyTask = 5,
  /// <summary>
  /// 三分大师赛任务
  /// </summary>
  [pbr::OriginalName("Task_ID_Three_Task")] ThreeTask = 6,
  /// <summary>
  /// 日活跃任务
  /// </summary>
  [pbr::OriginalName("Task_ID_Active_Task")] ActiveTask = 7,
  /// <summary>
  ///7日成长任务
  /// </summary>
  [pbr::OriginalName("Task_ID_Seven_Days_Task")] SevenDaysTask = 8,
}

public enum OrderStatus {
  /// <summary>
  ///开始充值
  /// </summary>
  [pbr::OriginalName("Begin")] Begin = 0,
  /// <summary>
  /// 收到回调  处理订单
  /// </summary>
  [pbr::OriginalName("Notify")] Notify = 1,
  /// <summary>
  /// 完成充值  给道具 通知客户端收到充值的道具了
  /// </summary>
  [pbr::OriginalName("Finish")] Finish = 2,
  /// <summary>
  ///客户端发送消息，通知服务器充值流程完毕
  /// </summary>
  [pbr::OriginalName("Publish")] Publish = 3,
}

public enum RedpointID {
  /// <summary>
  /// 无
  /// </summary>
  [pbr::OriginalName("nullRed")] NullRed = 0,
  /// <summary>
  ///主线任务       ChiledIds： questId
  /// </summary>
  [pbr::OriginalName("mainTask")] MainTask = 101,
  /// <summary>
  ///日常任务       ChiledIds： questId
  /// </summary>
  [pbr::OriginalName("dailyTask")] DailyTask = 102,
  /// <summary>
  ///三分大师赛任务 ChiledIds： questId
  /// </summary>
  [pbr::OriginalName("threeMasterTask")] ThreeMasterTask = 103,
  /// <summary>
  ///7日成长任务    ChiledIds： days
  /// </summary>
  [pbr::OriginalName("sevenDaysTask")] SevenDaysTask = 104,
  /// <summary>
  ///金币商店 
  /// </summary>
  [pbr::OriginalName("goldShop")] GoldShop = 201,
  /// <summary>
  ///钻石商店 		  
  /// </summary>
  [pbr::OriginalName("diamondShop")] DiamondShop = 202,
  /// <summary>
  ///礼包商店      
  /// </summary>
  [pbr::OriginalName("packetShop")] PacketShop = 203,
  /// <summary>
  ///充值商店
  /// </summary>
  [pbr::OriginalName("rechargeShop")] RechargeShop = 204,
  /// <summary>
  ///声望排行榜     ChiledIds： 下一个奖励id
  /// </summary>
  [pbr::OriginalName("reputationRank")] ReputationRank = 301,
  /// <summary>
  ///进阶赛         ChiledIds： 可以打的关卡id
  /// </summary>
  [pbr::OriginalName("matchinglv")] Matchinglv = 401,
  /// <summary>
  ///技能新增的技能    
  /// </summary>
  [pbr::OriginalName("skillNew")] SkillNew = 501,
  /// <summary>
  ///能升级的技能
  /// </summary>
  [pbr::OriginalName("skillLevelup")] SkillLevelup = 502,
  /// <summary>
  ///有可以装备的技能槽
  /// </summary>
  [pbr::OriginalName("skillEquipPos")] SkillEquipPos = 503,
  /// <summary>
  ///装备宝箱免费领取
  /// </summary>
  [pbr::OriginalName("equipmentBoxFree")] EquipmentBoxFree = 601,
  /// <summary>
  ///装备宝箱免费广告领取
  /// </summary>
  [pbr::OriginalName("equipmentBoxFreeAd")] EquipmentBoxFreeAd = 602,
  /// <summary>
  ///装备宝箱宝箱升级或升级抽奖
  /// </summary>
  [pbr::OriginalName("equipmentBoxLevelup")] EquipmentBoxLevelup = 603,
  /// <summary>
  ///装备宝箱10连抽
  /// </summary>
  [pbr::OriginalName("equipmentBoxTenDraw")] EquipmentBoxTenDraw = 604,
  /// <summary>
  ///邮件			  ChiledIds： 未领取附件的邮件id
  /// </summary>
  [pbr::OriginalName("mail")] Mail = 701,
  /// <summary>
  ///装备           ChiledIds： 新增的装备index
  /// </summary>
  [pbr::OriginalName("equipment")] Equipment = 801,
  /// <summary>
  ///对决赛表示对决比赛消耗道具已满 
  /// </summary>
  [pbr::OriginalName("detalDueItemMax")] DetalDueItemMax = 901,
  /// <summary>
  ///表示对决比赛段位奖励没有领
  /// </summary>
  [pbr::OriginalName("detalDueReward")] DetalDueReward = 902,
  /// <summary>
  ///技能宝箱免费领取
  /// </summary>
  [pbr::OriginalName("skillBoxFree")] SkillBoxFree = 1001,
  /// <summary>
  ///技能宝箱免费广告领取
  /// </summary>
  [pbr::OriginalName("skillBoxFreeAd")] SkillBoxFreeAd = 1002,
  /// <summary>
  ///技能宝箱10连抽
  /// </summary>
  [pbr::OriginalName("skillBoxTenDraw")] SkillBoxTenDraw = 1003,
  /// <summary>
  ///三分大师赛切换赛季
  /// </summary>
  [pbr::OriginalName("threeMasterSeason")] ThreeMasterSeason = 1101,
  /// <summary>
  ///爬塔扫荡普通次数
  /// </summary>
  [pbr::OriginalName("climbingTowerNormSweep")] ClimbingTowerNormSweep = 1201,
  /// <summary>
  ///爬塔扫荡广告次数
  /// </summary>
  [pbr::OriginalName("climbingTowerADSweep")] ClimbingTowerAdsweep = 1202,
  /// <summary>
  ///充值vip卡的每日奖励红点
  /// </summary>
  [pbr::OriginalName("rechargeVipCardDailyReward")] RechargeVipCardDailyReward = 1301,
  /// <summary>
  ///新手签到有可以签到的奖励 包括补签
  /// </summary>
  [pbr::OriginalName("newbieSignInAward")] NewbieSignInAward = 1401,
  /// <summary>
  ///7日签到有可以签到的奖励 包括补签
  /// </summary>
  [pbr::OriginalName("sevenDaysSignInAward")] SevenDaysSignInAward = 1402,
}

#endregion


#endregion Designer generated code
