// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: server.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from server.proto</summary>
public static partial class ServerReflection {

  #region Descriptor
  /// <summary>File descriptor for server.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ServerReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxzZXJ2ZXIucHJvdG8aDGNvbW1vbi5wcm90byLnAQoKU2VydmVySW5mbxIK",
          "CgJpZBgBIAEoBRIMCgRuYW1lGAMgASgJEg8KB2NtZEFkZHIYBCABKAkSDwoH",
          "cnBjQWRkchgFIAEoCRIPCgdleHRBZGRyGAYgASgJEhAKCGxhc3RUaWNrGAcg",
          "ASgDEhIKCnNlcnZlclR5cGUYCCABKAkSDAoEbG9hZBgJIAEoBRIMCgRjb25m",
          "GAogASgJEhMKC29ubGluZUNvdW50GAsgASgFEgsKA21kNRgMIAEoCRIMCgRh",
          "cmVhGA0gASgFEgoKAm9rGA4gASgIEg4KBndzQWRkchgPIAEoCSJWChBMZWFk",
          "ZXJib2FyZFNjb3JlEg8KB3VzZXJfaWQYASABKAkSDQoFc2NvcmUYAiABKAES",
          "EQoJdGltZXN0YW1wGAMgASgDEg8KB3JhbmtpbmcYBCABKAUiOQoUTGVhZGVy",
          "Ym9hcmRTY29yZUxpc3QSIQoGc2NvcmVzGAEgAygLMhEuTGVhZGVyYm9hcmRT",
          "Y29yZSI7ChNMb2dpYzJMb2dpY01haWxJbmZvEgsKA2dpZBgBIAEoBRIXCgRt",
          "YWlsGAIgASgLMgkuTWFpbEluZm8iTQobVG9uU2VydmVyU2VuZDJMb2dpY09y",
          "ZGVyTXNnEgsKA2dpZBgBIAEoBRIhCgNtc2cYAiABKAsyFC5Ub25SZWNoYXJn",
          "ZU9yZGVyTXNnQgZaBC4vcGJiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::CommonReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ServerInfo), global::ServerInfo.Parser, new[]{ "Id", "Name", "CmdAddr", "RpcAddr", "ExtAddr", "LastTick", "ServerType", "Load", "Conf", "OnlineCount", "Md5", "Area", "Ok", "WsAddr" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LeaderboardScore), global::LeaderboardScore.Parser, new[]{ "UserId", "Score", "Timestamp", "Ranking" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LeaderboardScoreList), global::LeaderboardScoreList.Parser, new[]{ "Scores" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Logic2LogicMailInfo), global::Logic2LogicMailInfo.Parser, new[]{ "Gid", "Mail" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::TonServerSend2LogicOrderMsg), global::TonServerSend2LogicOrderMsg.Parser, new[]{ "Gid", "Msg" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ServerInfo : pb::IMessage<ServerInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ServerInfo> _parser = new pb::MessageParser<ServerInfo>(() => new ServerInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ServerInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerInfo(ServerInfo other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    cmdAddr_ = other.cmdAddr_;
    rpcAddr_ = other.rpcAddr_;
    extAddr_ = other.extAddr_;
    lastTick_ = other.lastTick_;
    serverType_ = other.serverType_;
    load_ = other.load_;
    conf_ = other.conf_;
    onlineCount_ = other.onlineCount_;
    md5_ = other.md5_;
    area_ = other.area_;
    ok_ = other.ok_;
    wsAddr_ = other.wsAddr_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerInfo Clone() {
    return new ServerInfo(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  /// <summary>
  ///服务器id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 3;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "cmdAddr" field.</summary>
  public const int CmdAddrFieldNumber = 4;
  private string cmdAddr_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CmdAddr {
    get { return cmdAddr_; }
    set {
      cmdAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "rpcAddr" field.</summary>
  public const int RpcAddrFieldNumber = 5;
  private string rpcAddr_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RpcAddr {
    get { return rpcAddr_; }
    set {
      rpcAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "extAddr" field.</summary>
  public const int ExtAddrFieldNumber = 6;
  private string extAddr_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ExtAddr {
    get { return extAddr_; }
    set {
      extAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "lastTick" field.</summary>
  public const int LastTickFieldNumber = 7;
  private long lastTick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long LastTick {
    get { return lastTick_; }
    set {
      lastTick_ = value;
    }
  }

  /// <summary>Field number for the "serverType" field.</summary>
  public const int ServerTypeFieldNumber = 8;
  private string serverType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ServerType {
    get { return serverType_; }
    set {
      serverType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "load" field.</summary>
  public const int LoadFieldNumber = 9;
  private int load_;
  /// <summary>
  ///负载
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Load {
    get { return load_; }
    set {
      load_ = value;
    }
  }

  /// <summary>Field number for the "conf" field.</summary>
  public const int ConfFieldNumber = 10;
  private string conf_ = "";
  /// <summary>
  ///配置文件
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Conf {
    get { return conf_; }
    set {
      conf_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "onlineCount" field.</summary>
  public const int OnlineCountFieldNumber = 11;
  private int onlineCount_;
  /// <summary>
  ///在线玩家
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int OnlineCount {
    get { return onlineCount_; }
    set {
      onlineCount_ = value;
    }
  }

  /// <summary>Field number for the "md5" field.</summary>
  public const int Md5FieldNumber = 12;
  private string md5_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Md5 {
    get { return md5_; }
    set {
      md5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "area" field.</summary>
  public const int AreaFieldNumber = 13;
  private int area_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Area {
    get { return area_; }
    set {
      area_ = value;
    }
  }

  /// <summary>Field number for the "ok" field.</summary>
  public const int OkFieldNumber = 14;
  private bool ok_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Ok {
    get { return ok_; }
    set {
      ok_ = value;
    }
  }

  /// <summary>Field number for the "wsAddr" field.</summary>
  public const int WsAddrFieldNumber = 15;
  private string wsAddr_ = "";
  /// <summary>
  ///ws地址
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string WsAddr {
    get { return wsAddr_; }
    set {
      wsAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ServerInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ServerInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    if (CmdAddr != other.CmdAddr) return false;
    if (RpcAddr != other.RpcAddr) return false;
    if (ExtAddr != other.ExtAddr) return false;
    if (LastTick != other.LastTick) return false;
    if (ServerType != other.ServerType) return false;
    if (Load != other.Load) return false;
    if (Conf != other.Conf) return false;
    if (OnlineCount != other.OnlineCount) return false;
    if (Md5 != other.Md5) return false;
    if (Area != other.Area) return false;
    if (Ok != other.Ok) return false;
    if (WsAddr != other.WsAddr) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (CmdAddr.Length != 0) hash ^= CmdAddr.GetHashCode();
    if (RpcAddr.Length != 0) hash ^= RpcAddr.GetHashCode();
    if (ExtAddr.Length != 0) hash ^= ExtAddr.GetHashCode();
    if (LastTick != 0L) hash ^= LastTick.GetHashCode();
    if (ServerType.Length != 0) hash ^= ServerType.GetHashCode();
    if (Load != 0) hash ^= Load.GetHashCode();
    if (Conf.Length != 0) hash ^= Conf.GetHashCode();
    if (OnlineCount != 0) hash ^= OnlineCount.GetHashCode();
    if (Md5.Length != 0) hash ^= Md5.GetHashCode();
    if (Area != 0) hash ^= Area.GetHashCode();
    if (Ok != false) hash ^= Ok.GetHashCode();
    if (WsAddr.Length != 0) hash ^= WsAddr.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (CmdAddr.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(CmdAddr);
    }
    if (RpcAddr.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(RpcAddr);
    }
    if (ExtAddr.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(ExtAddr);
    }
    if (LastTick != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(LastTick);
    }
    if (ServerType.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(ServerType);
    }
    if (Load != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(Load);
    }
    if (Conf.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(Conf);
    }
    if (OnlineCount != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(OnlineCount);
    }
    if (Md5.Length != 0) {
      output.WriteRawTag(98);
      output.WriteString(Md5);
    }
    if (Area != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(Area);
    }
    if (Ok != false) {
      output.WriteRawTag(112);
      output.WriteBool(Ok);
    }
    if (WsAddr.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(WsAddr);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Name);
    }
    if (CmdAddr.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(CmdAddr);
    }
    if (RpcAddr.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(RpcAddr);
    }
    if (ExtAddr.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(ExtAddr);
    }
    if (LastTick != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(LastTick);
    }
    if (ServerType.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(ServerType);
    }
    if (Load != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(Load);
    }
    if (Conf.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(Conf);
    }
    if (OnlineCount != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(OnlineCount);
    }
    if (Md5.Length != 0) {
      output.WriteRawTag(98);
      output.WriteString(Md5);
    }
    if (Area != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(Area);
    }
    if (Ok != false) {
      output.WriteRawTag(112);
      output.WriteBool(Ok);
    }
    if (WsAddr.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(WsAddr);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (CmdAddr.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CmdAddr);
    }
    if (RpcAddr.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RpcAddr);
    }
    if (ExtAddr.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ExtAddr);
    }
    if (LastTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastTick);
    }
    if (ServerType.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ServerType);
    }
    if (Load != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Load);
    }
    if (Conf.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Conf);
    }
    if (OnlineCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(OnlineCount);
    }
    if (Md5.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Md5);
    }
    if (Area != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Area);
    }
    if (Ok != false) {
      size += 1 + 1;
    }
    if (WsAddr.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(WsAddr);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ServerInfo other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.CmdAddr.Length != 0) {
      CmdAddr = other.CmdAddr;
    }
    if (other.RpcAddr.Length != 0) {
      RpcAddr = other.RpcAddr;
    }
    if (other.ExtAddr.Length != 0) {
      ExtAddr = other.ExtAddr;
    }
    if (other.LastTick != 0L) {
      LastTick = other.LastTick;
    }
    if (other.ServerType.Length != 0) {
      ServerType = other.ServerType;
    }
    if (other.Load != 0) {
      Load = other.Load;
    }
    if (other.Conf.Length != 0) {
      Conf = other.Conf;
    }
    if (other.OnlineCount != 0) {
      OnlineCount = other.OnlineCount;
    }
    if (other.Md5.Length != 0) {
      Md5 = other.Md5;
    }
    if (other.Area != 0) {
      Area = other.Area;
    }
    if (other.Ok != false) {
      Ok = other.Ok;
    }
    if (other.WsAddr.Length != 0) {
      WsAddr = other.WsAddr;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          CmdAddr = input.ReadString();
          break;
        }
        case 42: {
          RpcAddr = input.ReadString();
          break;
        }
        case 50: {
          ExtAddr = input.ReadString();
          break;
        }
        case 56: {
          LastTick = input.ReadInt64();
          break;
        }
        case 66: {
          ServerType = input.ReadString();
          break;
        }
        case 72: {
          Load = input.ReadInt32();
          break;
        }
        case 82: {
          Conf = input.ReadString();
          break;
        }
        case 88: {
          OnlineCount = input.ReadInt32();
          break;
        }
        case 98: {
          Md5 = input.ReadString();
          break;
        }
        case 104: {
          Area = input.ReadInt32();
          break;
        }
        case 112: {
          Ok = input.ReadBool();
          break;
        }
        case 122: {
          WsAddr = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 26: {
          Name = input.ReadString();
          break;
        }
        case 34: {
          CmdAddr = input.ReadString();
          break;
        }
        case 42: {
          RpcAddr = input.ReadString();
          break;
        }
        case 50: {
          ExtAddr = input.ReadString();
          break;
        }
        case 56: {
          LastTick = input.ReadInt64();
          break;
        }
        case 66: {
          ServerType = input.ReadString();
          break;
        }
        case 72: {
          Load = input.ReadInt32();
          break;
        }
        case 82: {
          Conf = input.ReadString();
          break;
        }
        case 88: {
          OnlineCount = input.ReadInt32();
          break;
        }
        case 98: {
          Md5 = input.ReadString();
          break;
        }
        case 104: {
          Area = input.ReadInt32();
          break;
        }
        case 112: {
          Ok = input.ReadBool();
          break;
        }
        case 122: {
          WsAddr = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LeaderboardScore : pb::IMessage<LeaderboardScore>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LeaderboardScore> _parser = new pb::MessageParser<LeaderboardScore>(() => new LeaderboardScore());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LeaderboardScore> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LeaderboardScore() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LeaderboardScore(LeaderboardScore other) : this() {
    userId_ = other.userId_;
    score_ = other.score_;
    timestamp_ = other.timestamp_;
    ranking_ = other.ranking_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LeaderboardScore Clone() {
    return new LeaderboardScore(this);
  }

  /// <summary>Field number for the "user_id" field.</summary>
  public const int UserIdFieldNumber = 1;
  private string userId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserId {
    get { return userId_; }
    set {
      userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "score" field.</summary>
  public const int ScoreFieldNumber = 2;
  private double score_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Score {
    get { return score_; }
    set {
      score_ = value;
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 3;
  private long timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "ranking" field.</summary>
  public const int RankingFieldNumber = 4;
  private int ranking_;
  /// <summary>
  ///排名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Ranking {
    get { return ranking_; }
    set {
      ranking_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LeaderboardScore);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LeaderboardScore other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserId != other.UserId) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Score, other.Score)) return false;
    if (Timestamp != other.Timestamp) return false;
    if (Ranking != other.Ranking) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (UserId.Length != 0) hash ^= UserId.GetHashCode();
    if (Score != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Score);
    if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
    if (Ranking != 0) hash ^= Ranking.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (UserId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserId);
    }
    if (Score != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Score);
    }
    if (Timestamp != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Timestamp);
    }
    if (Ranking != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Ranking);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (UserId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserId);
    }
    if (Score != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Score);
    }
    if (Timestamp != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Timestamp);
    }
    if (Ranking != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Ranking);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (UserId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
    }
    if (Score != 0D) {
      size += 1 + 8;
    }
    if (Timestamp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
    }
    if (Ranking != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Ranking);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LeaderboardScore other) {
    if (other == null) {
      return;
    }
    if (other.UserId.Length != 0) {
      UserId = other.UserId;
    }
    if (other.Score != 0D) {
      Score = other.Score;
    }
    if (other.Timestamp != 0L) {
      Timestamp = other.Timestamp;
    }
    if (other.Ranking != 0) {
      Ranking = other.Ranking;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserId = input.ReadString();
          break;
        }
        case 17: {
          Score = input.ReadDouble();
          break;
        }
        case 24: {
          Timestamp = input.ReadInt64();
          break;
        }
        case 32: {
          Ranking = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          UserId = input.ReadString();
          break;
        }
        case 17: {
          Score = input.ReadDouble();
          break;
        }
        case 24: {
          Timestamp = input.ReadInt64();
          break;
        }
        case 32: {
          Ranking = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LeaderboardScoreList : pb::IMessage<LeaderboardScoreList>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LeaderboardScoreList> _parser = new pb::MessageParser<LeaderboardScoreList>(() => new LeaderboardScoreList());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LeaderboardScoreList> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LeaderboardScoreList() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LeaderboardScoreList(LeaderboardScoreList other) : this() {
    scores_ = other.scores_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LeaderboardScoreList Clone() {
    return new LeaderboardScoreList(this);
  }

  /// <summary>Field number for the "scores" field.</summary>
  public const int ScoresFieldNumber = 1;
  private static readonly pb::FieldCodec<global::LeaderboardScore> _repeated_scores_codec
      = pb::FieldCodec.ForMessage(10, global::LeaderboardScore.Parser);
  private readonly pbc::RepeatedField<global::LeaderboardScore> scores_ = new pbc::RepeatedField<global::LeaderboardScore>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::LeaderboardScore> Scores {
    get { return scores_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LeaderboardScoreList);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LeaderboardScoreList other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!scores_.Equals(other.scores_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= scores_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    scores_.WriteTo(output, _repeated_scores_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    scores_.WriteTo(ref output, _repeated_scores_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += scores_.CalculateSize(_repeated_scores_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LeaderboardScoreList other) {
    if (other == null) {
      return;
    }
    scores_.Add(other.scores_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          scores_.AddEntriesFrom(input, _repeated_scores_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          scores_.AddEntriesFrom(ref input, _repeated_scores_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Logic2LogicMailInfo : pb::IMessage<Logic2LogicMailInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Logic2LogicMailInfo> _parser = new pb::MessageParser<Logic2LogicMailInfo>(() => new Logic2LogicMailInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Logic2LogicMailInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Logic2LogicMailInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Logic2LogicMailInfo(Logic2LogicMailInfo other) : this() {
    gid_ = other.gid_;
    mail_ = other.mail_ != null ? other.mail_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Logic2LogicMailInfo Clone() {
    return new Logic2LogicMailInfo(this);
  }

  /// <summary>Field number for the "gid" field.</summary>
  public const int GidFieldNumber = 1;
  private int gid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gid {
    get { return gid_; }
    set {
      gid_ = value;
    }
  }

  /// <summary>Field number for the "mail" field.</summary>
  public const int MailFieldNumber = 2;
  private global::MailInfo mail_;
  /// <summary>
  ///邮件信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MailInfo Mail {
    get { return mail_; }
    set {
      mail_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Logic2LogicMailInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Logic2LogicMailInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Gid != other.Gid) return false;
    if (!object.Equals(Mail, other.Mail)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Gid != 0) hash ^= Gid.GetHashCode();
    if (mail_ != null) hash ^= Mail.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Gid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Gid);
    }
    if (mail_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Mail);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Gid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Gid);
    }
    if (mail_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Mail);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Gid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gid);
    }
    if (mail_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mail);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Logic2LogicMailInfo other) {
    if (other == null) {
      return;
    }
    if (other.Gid != 0) {
      Gid = other.Gid;
    }
    if (other.mail_ != null) {
      if (mail_ == null) {
        Mail = new global::MailInfo();
      }
      Mail.MergeFrom(other.Mail);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Gid = input.ReadInt32();
          break;
        }
        case 18: {
          if (mail_ == null) {
            Mail = new global::MailInfo();
          }
          input.ReadMessage(Mail);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Gid = input.ReadInt32();
          break;
        }
        case 18: {
          if (mail_ == null) {
            Mail = new global::MailInfo();
          }
          input.ReadMessage(Mail);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class TonServerSend2LogicOrderMsg : pb::IMessage<TonServerSend2LogicOrderMsg>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<TonServerSend2LogicOrderMsg> _parser = new pb::MessageParser<TonServerSend2LogicOrderMsg>(() => new TonServerSend2LogicOrderMsg());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<TonServerSend2LogicOrderMsg> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TonServerSend2LogicOrderMsg() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TonServerSend2LogicOrderMsg(TonServerSend2LogicOrderMsg other) : this() {
    gid_ = other.gid_;
    msg_ = other.msg_ != null ? other.msg_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TonServerSend2LogicOrderMsg Clone() {
    return new TonServerSend2LogicOrderMsg(this);
  }

  /// <summary>Field number for the "gid" field.</summary>
  public const int GidFieldNumber = 1;
  private int gid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gid {
    get { return gid_; }
    set {
      gid_ = value;
    }
  }

  /// <summary>Field number for the "msg" field.</summary>
  public const int MsgFieldNumber = 2;
  private global::TonRechargeOrderMsg msg_;
  /// <summary>
  ///ton的orderMsg
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::TonRechargeOrderMsg Msg {
    get { return msg_; }
    set {
      msg_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as TonServerSend2LogicOrderMsg);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(TonServerSend2LogicOrderMsg other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Gid != other.Gid) return false;
    if (!object.Equals(Msg, other.Msg)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Gid != 0) hash ^= Gid.GetHashCode();
    if (msg_ != null) hash ^= Msg.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Gid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Gid);
    }
    if (msg_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Msg);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Gid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Gid);
    }
    if (msg_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Msg);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Gid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gid);
    }
    if (msg_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Msg);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(TonServerSend2LogicOrderMsg other) {
    if (other == null) {
      return;
    }
    if (other.Gid != 0) {
      Gid = other.Gid;
    }
    if (other.msg_ != null) {
      if (msg_ == null) {
        Msg = new global::TonRechargeOrderMsg();
      }
      Msg.MergeFrom(other.Msg);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Gid = input.ReadInt32();
          break;
        }
        case 18: {
          if (msg_ == null) {
            Msg = new global::TonRechargeOrderMsg();
          }
          input.ReadMessage(Msg);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Gid = input.ReadInt32();
          break;
        }
        case 18: {
          if (msg_ == null) {
            Msg = new global::TonRechargeOrderMsg();
          }
          input.ReadMessage(Msg);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
