// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: auth.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from auth.proto</summary>
public static partial class AuthReflection {

  #region Descriptor
  /// <summary>File descriptor for auth.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AuthReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgphdXRoLnByb3RvGgttYWNyby5wcm90byI0CghVc2VySW5mbxIMCgRuYW1l",
          "GAEgASgJEg4KBnBhc3N3ZBgCIAEoCRIKCgJpZBgDIAEoCSJ0CgxVc2VyUm9s",
          "ZUluZm8SCgoCaWQYASABKAUSDAoEbmFtZRgCIAEoCRIOCgZzZXJ2ZXIYAyAB",
          "KAUSDQoFY3RpbWUYBCABKAMSCwoDdWlkGAUgASgJEg4KBnR5cGVJZBgGIAEo",
          "BRIOCgZzdGF0dXMYByABKAUi9gEKD0xvZ2ljU2VydmVySW5mbxIKCgJpZBgB",
          "IAEoBRIMCgRuYW1lGAIgASgJEg0KBXN0YXJ0GAMgASgDEgsKA2VuZBgEIAEo",
          "AxIMCgR0aW1lGAUgASgDEhwKBXN0YXRlGAYgASgOMg0uU2VydmVyU3RhdHVz",
          "EhIKCmN5Y2xlU3RhcnQYByABKAMSEAoIY3ljbGVFbmQYCCABKAMSDwoHaXND",
          "eWNsZRgJIAEoCBIXCgN0YWcYCiABKA4yCi5TZXJ2ZXJUYWcSDwoHbm9NYXRj",
          "aBgLIAEoCBIgCgdjaGFubmVsGAwgASgOMg8uQ2hhbm5lbEFsbFR5cGUiZwoR",
          "U2VydmVyQ2hhbm5lbEluZm8SGAoCaWQYASABKA4yDC5DaGFubmVsVHlwZRIN",
          "CgVjbG9zZRgCIAEoCBILCgNtc2cYAyABKAkSDQoFbXNnT1AYBCABKAMSDQoF",
          "bXNnRUQYBSABKAMiKAoMU3VwZXJBY2NvdW50EgsKA3VpZBgBIAEoCRILCgNn",
          "aWQYAiABKAUiOgoETGluZRIMCgRsc2lkGAEgASgFEgoKAm9uGAIgASgIEgsK",
          "A21pbhgDIAEoBRILCgNtYXgYBCABKAUiLAoKT25saW5lVGltZRIMCgRkYXRl",
          "GAEgASgJEhAKCGR1cmF0aW9uGAIgASgDIsYBCgdVSURJbmZvEgsKA3VpZBgB",
          "IAEoCRIUCgxyZWFsTmFtZVNpZ24YAiABKAUSCgoCaWQYAyABKAkSIwoOb25s",
          "aW5lVGltZURhdGEYBCADKAsyCy5PbmxpbmVUaW1lEhEKCWF1dGhDb3VudBgF",
          "IAEoBRIQCghhdXRoVGltZRgGIAEoAxIXCg90b3RhbE9ubGluZVRpbWUYByAB",
          "KAMSEQoJcm5jU3RhdHVzGAggASgFEhYKDnRvdGFsRmFpbENvdW50GAkgASgF",
          "QgZaBC4vcGJiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::MacroReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::UserInfo), global::UserInfo.Parser, new[]{ "Name", "Passwd", "Id" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UserRoleInfo), global::UserRoleInfo.Parser, new[]{ "Id", "Name", "Server", "Ctime", "Uid", "TypeId", "Status" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LogicServerInfo), global::LogicServerInfo.Parser, new[]{ "Id", "Name", "Start", "End", "Time", "State", "CycleStart", "CycleEnd", "IsCycle", "Tag", "NoMatch", "Channel" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ServerChannelInfo), global::ServerChannelInfo.Parser, new[]{ "Id", "Close", "Msg", "MsgOP", "MsgED" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SuperAccount), global::SuperAccount.Parser, new[]{ "Uid", "Gid" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Line), global::Line.Parser, new[]{ "Lsid", "On", "Min", "Max" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::OnlineTime), global::OnlineTime.Parser, new[]{ "Date", "Duration" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UIDInfo), global::UIDInfo.Parser, new[]{ "Uid", "RealNameSign", "Id", "OnlineTimeData", "AuthCount", "AuthTime", "TotalOnlineTime", "RncStatus", "TotalFailCount" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class UserInfo : pb::IMessage<UserInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserInfo> _parser = new pb::MessageParser<UserInfo>(() => new UserInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserInfo(UserInfo other) : this() {
    name_ = other.name_;
    passwd_ = other.passwd_;
    id_ = other.id_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserInfo Clone() {
    return new UserInfo(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  /// <summary>
  ///玩家名字
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "passwd" field.</summary>
  public const int PasswdFieldNumber = 2;
  private string passwd_ = "";
  /// <summary>
  ///玩家密码
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Passwd {
    get { return passwd_; }
    set {
      passwd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 3;
  private string id_ = "";
  /// <summary>
  ///玩家id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Passwd != other.Passwd) return false;
    if (Id != other.Id) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Passwd.Length != 0) hash ^= Passwd.GetHashCode();
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Passwd.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Passwd);
    }
    if (Id.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Id);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Passwd.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Passwd);
    }
    if (Id.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Id);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Passwd.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Passwd);
    }
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserInfo other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Passwd.Length != 0) {
      Passwd = other.Passwd;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Passwd = input.ReadString();
          break;
        }
        case 26: {
          Id = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Passwd = input.ReadString();
          break;
        }
        case 26: {
          Id = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class UserRoleInfo : pb::IMessage<UserRoleInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserRoleInfo> _parser = new pb::MessageParser<UserRoleInfo>(() => new UserRoleInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserRoleInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserRoleInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserRoleInfo(UserRoleInfo other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    server_ = other.server_;
    ctime_ = other.ctime_;
    uid_ = other.uid_;
    typeId_ = other.typeId_;
    status_ = other.status_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserRoleInfo Clone() {
    return new UserRoleInfo(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  /// <summary>
  ///角色id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  /// <summary>
  ///角色昵称	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "server" field.</summary>
  public const int ServerFieldNumber = 3;
  private int server_;
  /// <summary>
  ///角色所在服务器
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Server {
    get { return server_; }
    set {
      server_ = value;
    }
  }

  /// <summary>Field number for the "ctime" field.</summary>
  public const int CtimeFieldNumber = 4;
  private long ctime_;
  /// <summary>
  ///角色创建时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Ctime {
    get { return ctime_; }
    set {
      ctime_ = value;
    }
  }

  /// <summary>Field number for the "uid" field.</summary>
  public const int UidFieldNumber = 5;
  private string uid_ = "";
  /// <summary>
  ///玩家id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Uid {
    get { return uid_; }
    set {
      uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "typeId" field.</summary>
  public const int TypeIdFieldNumber = 6;
  private int typeId_;
  /// <summary>
  ///角色类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TypeId {
    get { return typeId_; }
    set {
      typeId_ = value;
    }
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 7;
  private int status_;
  /// <summary>
  ///预创角色状态(0-正常玩家 1-预创角色玩家 2-已走新手引导预创角色玩家)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserRoleInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserRoleInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    if (Server != other.Server) return false;
    if (Ctime != other.Ctime) return false;
    if (Uid != other.Uid) return false;
    if (TypeId != other.TypeId) return false;
    if (Status != other.Status) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Server != 0) hash ^= Server.GetHashCode();
    if (Ctime != 0L) hash ^= Ctime.GetHashCode();
    if (Uid.Length != 0) hash ^= Uid.GetHashCode();
    if (TypeId != 0) hash ^= TypeId.GetHashCode();
    if (Status != 0) hash ^= Status.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Server != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Server);
    }
    if (Ctime != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Ctime);
    }
    if (Uid.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Uid);
    }
    if (TypeId != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(TypeId);
    }
    if (Status != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Status);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Server != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Server);
    }
    if (Ctime != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Ctime);
    }
    if (Uid.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Uid);
    }
    if (TypeId != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(TypeId);
    }
    if (Status != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Status);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Server != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Server);
    }
    if (Ctime != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Ctime);
    }
    if (Uid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
    }
    if (TypeId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TypeId);
    }
    if (Status != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserRoleInfo other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Server != 0) {
      Server = other.Server;
    }
    if (other.Ctime != 0L) {
      Ctime = other.Ctime;
    }
    if (other.Uid.Length != 0) {
      Uid = other.Uid;
    }
    if (other.TypeId != 0) {
      TypeId = other.TypeId;
    }
    if (other.Status != 0) {
      Status = other.Status;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 24: {
          Server = input.ReadInt32();
          break;
        }
        case 32: {
          Ctime = input.ReadInt64();
          break;
        }
        case 42: {
          Uid = input.ReadString();
          break;
        }
        case 48: {
          TypeId = input.ReadInt32();
          break;
        }
        case 56: {
          Status = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 24: {
          Server = input.ReadInt32();
          break;
        }
        case 32: {
          Ctime = input.ReadInt64();
          break;
        }
        case 42: {
          Uid = input.ReadString();
          break;
        }
        case 48: {
          TypeId = input.ReadInt32();
          break;
        }
        case 56: {
          Status = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LogicServerInfo : pb::IMessage<LogicServerInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LogicServerInfo> _parser = new pb::MessageParser<LogicServerInfo>(() => new LogicServerInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LogicServerInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogicServerInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogicServerInfo(LogicServerInfo other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    start_ = other.start_;
    end_ = other.end_;
    time_ = other.time_;
    state_ = other.state_;
    cycleStart_ = other.cycleStart_;
    cycleEnd_ = other.cycleEnd_;
    isCycle_ = other.isCycle_;
    tag_ = other.tag_;
    noMatch_ = other.noMatch_;
    channel_ = other.channel_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogicServerInfo Clone() {
    return new LogicServerInfo(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  /// <summary>
  ///区服id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  /// <summary>
  ///区服名字
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "start" field.</summary>
  public const int StartFieldNumber = 3;
  private long start_;
  /// <summary>
  ///启动时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Start {
    get { return start_; }
    set {
      start_ = value;
    }
  }

  /// <summary>Field number for the "end" field.</summary>
  public const int EndFieldNumber = 4;
  private long end_;
  /// <summary>
  ///关闭时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long End {
    get { return end_; }
    set {
      end_ = value;
    }
  }

  /// <summary>Field number for the "time" field.</summary>
  public const int TimeFieldNumber = 5;
  private long time_;
  /// <summary>
  ///区服创建时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Time {
    get { return time_; }
    set {
      time_ = value;
    }
  }

  /// <summary>Field number for the "state" field.</summary>
  public const int StateFieldNumber = 6;
  private global::ServerStatus state_ = global::ServerStatus.Fix;
  /// <summary>
  ///火爆等
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ServerStatus State {
    get { return state_; }
    set {
      state_ = value;
    }
  }

  /// <summary>Field number for the "cycleStart" field.</summary>
  public const int CycleStartFieldNumber = 7;
  private long cycleStart_;
  /// <summary>
  ///每日开服的秒数
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long CycleStart {
    get { return cycleStart_; }
    set {
      cycleStart_ = value;
    }
  }

  /// <summary>Field number for the "cycleEnd" field.</summary>
  public const int CycleEndFieldNumber = 8;
  private long cycleEnd_;
  /// <summary>
  ///每日关服的秒数
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long CycleEnd {
    get { return cycleEnd_; }
    set {
      cycleEnd_ = value;
    }
  }

  /// <summary>Field number for the "isCycle" field.</summary>
  public const int IsCycleFieldNumber = 9;
  private bool isCycle_;
  /// <summary>
  ///是否周期开服
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsCycle {
    get { return isCycle_; }
    set {
      isCycle_ = value;
    }
  }

  /// <summary>Field number for the "tag" field.</summary>
  public const int TagFieldNumber = 10;
  private global::ServerTag tag_ = global::ServerTag.ServerNoTag;
  /// <summary>
  ///标签
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ServerTag Tag {
    get { return tag_; }
    set {
      tag_ = value;
    }
  }

  /// <summary>Field number for the "noMatch" field.</summary>
  public const int NoMatchFieldNumber = 11;
  private bool noMatch_;
  /// <summary>
  ///是否关闭匹配
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool NoMatch {
    get { return noMatch_; }
    set {
      noMatch_ = value;
    }
  }

  /// <summary>Field number for the "channel" field.</summary>
  public const int ChannelFieldNumber = 12;
  private global::ChannelAllType channel_ = global::ChannelAllType.ChannelAllIosandroid;
  /// <summary>
  ///渠道
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ChannelAllType Channel {
    get { return channel_; }
    set {
      channel_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LogicServerInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LogicServerInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    if (Start != other.Start) return false;
    if (End != other.End) return false;
    if (Time != other.Time) return false;
    if (State != other.State) return false;
    if (CycleStart != other.CycleStart) return false;
    if (CycleEnd != other.CycleEnd) return false;
    if (IsCycle != other.IsCycle) return false;
    if (Tag != other.Tag) return false;
    if (NoMatch != other.NoMatch) return false;
    if (Channel != other.Channel) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Start != 0L) hash ^= Start.GetHashCode();
    if (End != 0L) hash ^= End.GetHashCode();
    if (Time != 0L) hash ^= Time.GetHashCode();
    if (State != global::ServerStatus.Fix) hash ^= State.GetHashCode();
    if (CycleStart != 0L) hash ^= CycleStart.GetHashCode();
    if (CycleEnd != 0L) hash ^= CycleEnd.GetHashCode();
    if (IsCycle != false) hash ^= IsCycle.GetHashCode();
    if (Tag != global::ServerTag.ServerNoTag) hash ^= Tag.GetHashCode();
    if (NoMatch != false) hash ^= NoMatch.GetHashCode();
    if (Channel != global::ChannelAllType.ChannelAllIosandroid) hash ^= Channel.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Start != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Start);
    }
    if (End != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(End);
    }
    if (Time != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(Time);
    }
    if (State != global::ServerStatus.Fix) {
      output.WriteRawTag(48);
      output.WriteEnum((int) State);
    }
    if (CycleStart != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(CycleStart);
    }
    if (CycleEnd != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(CycleEnd);
    }
    if (IsCycle != false) {
      output.WriteRawTag(72);
      output.WriteBool(IsCycle);
    }
    if (Tag != global::ServerTag.ServerNoTag) {
      output.WriteRawTag(80);
      output.WriteEnum((int) Tag);
    }
    if (NoMatch != false) {
      output.WriteRawTag(88);
      output.WriteBool(NoMatch);
    }
    if (Channel != global::ChannelAllType.ChannelAllIosandroid) {
      output.WriteRawTag(96);
      output.WriteEnum((int) Channel);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Start != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Start);
    }
    if (End != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(End);
    }
    if (Time != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(Time);
    }
    if (State != global::ServerStatus.Fix) {
      output.WriteRawTag(48);
      output.WriteEnum((int) State);
    }
    if (CycleStart != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(CycleStart);
    }
    if (CycleEnd != 0L) {
      output.WriteRawTag(64);
      output.WriteInt64(CycleEnd);
    }
    if (IsCycle != false) {
      output.WriteRawTag(72);
      output.WriteBool(IsCycle);
    }
    if (Tag != global::ServerTag.ServerNoTag) {
      output.WriteRawTag(80);
      output.WriteEnum((int) Tag);
    }
    if (NoMatch != false) {
      output.WriteRawTag(88);
      output.WriteBool(NoMatch);
    }
    if (Channel != global::ChannelAllType.ChannelAllIosandroid) {
      output.WriteRawTag(96);
      output.WriteEnum((int) Channel);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Start != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Start);
    }
    if (End != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(End);
    }
    if (Time != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
    }
    if (State != global::ServerStatus.Fix) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
    }
    if (CycleStart != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(CycleStart);
    }
    if (CycleEnd != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(CycleEnd);
    }
    if (IsCycle != false) {
      size += 1 + 1;
    }
    if (Tag != global::ServerTag.ServerNoTag) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Tag);
    }
    if (NoMatch != false) {
      size += 1 + 1;
    }
    if (Channel != global::ChannelAllType.ChannelAllIosandroid) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Channel);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LogicServerInfo other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Start != 0L) {
      Start = other.Start;
    }
    if (other.End != 0L) {
      End = other.End;
    }
    if (other.Time != 0L) {
      Time = other.Time;
    }
    if (other.State != global::ServerStatus.Fix) {
      State = other.State;
    }
    if (other.CycleStart != 0L) {
      CycleStart = other.CycleStart;
    }
    if (other.CycleEnd != 0L) {
      CycleEnd = other.CycleEnd;
    }
    if (other.IsCycle != false) {
      IsCycle = other.IsCycle;
    }
    if (other.Tag != global::ServerTag.ServerNoTag) {
      Tag = other.Tag;
    }
    if (other.NoMatch != false) {
      NoMatch = other.NoMatch;
    }
    if (other.Channel != global::ChannelAllType.ChannelAllIosandroid) {
      Channel = other.Channel;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 24: {
          Start = input.ReadInt64();
          break;
        }
        case 32: {
          End = input.ReadInt64();
          break;
        }
        case 40: {
          Time = input.ReadInt64();
          break;
        }
        case 48: {
          State = (global::ServerStatus) input.ReadEnum();
          break;
        }
        case 56: {
          CycleStart = input.ReadInt64();
          break;
        }
        case 64: {
          CycleEnd = input.ReadInt64();
          break;
        }
        case 72: {
          IsCycle = input.ReadBool();
          break;
        }
        case 80: {
          Tag = (global::ServerTag) input.ReadEnum();
          break;
        }
        case 88: {
          NoMatch = input.ReadBool();
          break;
        }
        case 96: {
          Channel = (global::ChannelAllType) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 24: {
          Start = input.ReadInt64();
          break;
        }
        case 32: {
          End = input.ReadInt64();
          break;
        }
        case 40: {
          Time = input.ReadInt64();
          break;
        }
        case 48: {
          State = (global::ServerStatus) input.ReadEnum();
          break;
        }
        case 56: {
          CycleStart = input.ReadInt64();
          break;
        }
        case 64: {
          CycleEnd = input.ReadInt64();
          break;
        }
        case 72: {
          IsCycle = input.ReadBool();
          break;
        }
        case 80: {
          Tag = (global::ServerTag) input.ReadEnum();
          break;
        }
        case 88: {
          NoMatch = input.ReadBool();
          break;
        }
        case 96: {
          Channel = (global::ChannelAllType) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///渠道维护结构
/// </summary>
public sealed partial class ServerChannelInfo : pb::IMessage<ServerChannelInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ServerChannelInfo> _parser = new pb::MessageParser<ServerChannelInfo>(() => new ServerChannelInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ServerChannelInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerChannelInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerChannelInfo(ServerChannelInfo other) : this() {
    id_ = other.id_;
    close_ = other.close_;
    msg_ = other.msg_;
    msgOP_ = other.msgOP_;
    msgED_ = other.msgED_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerChannelInfo Clone() {
    return new ServerChannelInfo(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private global::ChannelType id_ = global::ChannelType.ChannelPc;
  /// <summary>
  ///小渠道id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ChannelType Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "close" field.</summary>
  public const int CloseFieldNumber = 2;
  private bool close_;
  /// <summary>
  ///是否关闭，true为关闭状态，此时属于此子渠道的玩家不能登录或游戏
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Close {
    get { return close_; }
    set {
      close_ = value;
    }
  }

  /// <summary>Field number for the "msg" field.</summary>
  public const int MsgFieldNumber = 3;
  private string msg_ = "";
  /// <summary>
  ///拦截公告
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Msg {
    get { return msg_; }
    set {
      msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "msgOP" field.</summary>
  public const int MsgOPFieldNumber = 4;
  private long msgOP_;
  /// <summary>
  ///公告开始时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long MsgOP {
    get { return msgOP_; }
    set {
      msgOP_ = value;
    }
  }

  /// <summary>Field number for the "msgED" field.</summary>
  public const int MsgEDFieldNumber = 5;
  private long msgED_;
  /// <summary>
  ///公告结束时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long MsgED {
    get { return msgED_; }
    set {
      msgED_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ServerChannelInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ServerChannelInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Close != other.Close) return false;
    if (Msg != other.Msg) return false;
    if (MsgOP != other.MsgOP) return false;
    if (MsgED != other.MsgED) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != global::ChannelType.ChannelPc) hash ^= Id.GetHashCode();
    if (Close != false) hash ^= Close.GetHashCode();
    if (Msg.Length != 0) hash ^= Msg.GetHashCode();
    if (MsgOP != 0L) hash ^= MsgOP.GetHashCode();
    if (MsgED != 0L) hash ^= MsgED.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != global::ChannelType.ChannelPc) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Id);
    }
    if (Close != false) {
      output.WriteRawTag(16);
      output.WriteBool(Close);
    }
    if (Msg.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Msg);
    }
    if (MsgOP != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(MsgOP);
    }
    if (MsgED != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(MsgED);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != global::ChannelType.ChannelPc) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Id);
    }
    if (Close != false) {
      output.WriteRawTag(16);
      output.WriteBool(Close);
    }
    if (Msg.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Msg);
    }
    if (MsgOP != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(MsgOP);
    }
    if (MsgED != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(MsgED);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != global::ChannelType.ChannelPc) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id);
    }
    if (Close != false) {
      size += 1 + 1;
    }
    if (Msg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
    }
    if (MsgOP != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(MsgOP);
    }
    if (MsgED != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(MsgED);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ServerChannelInfo other) {
    if (other == null) {
      return;
    }
    if (other.Id != global::ChannelType.ChannelPc) {
      Id = other.Id;
    }
    if (other.Close != false) {
      Close = other.Close;
    }
    if (other.Msg.Length != 0) {
      Msg = other.Msg;
    }
    if (other.MsgOP != 0L) {
      MsgOP = other.MsgOP;
    }
    if (other.MsgED != 0L) {
      MsgED = other.MsgED;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = (global::ChannelType) input.ReadEnum();
          break;
        }
        case 16: {
          Close = input.ReadBool();
          break;
        }
        case 26: {
          Msg = input.ReadString();
          break;
        }
        case 32: {
          MsgOP = input.ReadInt64();
          break;
        }
        case 40: {
          MsgED = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = (global::ChannelType) input.ReadEnum();
          break;
        }
        case 16: {
          Close = input.ReadBool();
          break;
        }
        case 26: {
          Msg = input.ReadString();
          break;
        }
        case 32: {
          MsgOP = input.ReadInt64();
          break;
        }
        case 40: {
          MsgED = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class SuperAccount : pb::IMessage<SuperAccount>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SuperAccount> _parser = new pb::MessageParser<SuperAccount>(() => new SuperAccount());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SuperAccount> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SuperAccount() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SuperAccount(SuperAccount other) : this() {
    uid_ = other.uid_;
    gid_ = other.gid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SuperAccount Clone() {
    return new SuperAccount(this);
  }

  /// <summary>Field number for the "uid" field.</summary>
  public const int UidFieldNumber = 1;
  private string uid_ = "";
  /// <summary>
  ///账号密码所对应的uid
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Uid {
    get { return uid_; }
    set {
      uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "gid" field.</summary>
  public const int GidFieldNumber = 2;
  private int gid_;
  /// <summary>
  ///需要查看的gid
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Gid {
    get { return gid_; }
    set {
      gid_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SuperAccount);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SuperAccount other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Uid != other.Uid) return false;
    if (Gid != other.Gid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Uid.Length != 0) hash ^= Uid.GetHashCode();
    if (Gid != 0) hash ^= Gid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Uid.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Uid);
    }
    if (Gid != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Gid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Uid.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Uid);
    }
    if (Gid != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Gid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Uid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
    }
    if (Gid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SuperAccount other) {
    if (other == null) {
      return;
    }
    if (other.Uid.Length != 0) {
      Uid = other.Uid;
    }
    if (other.Gid != 0) {
      Gid = other.Gid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Uid = input.ReadString();
          break;
        }
        case 16: {
          Gid = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Uid = input.ReadString();
          break;
        }
        case 16: {
          Gid = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///排队
/// </summary>
public sealed partial class Line : pb::IMessage<Line>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Line> _parser = new pb::MessageParser<Line>(() => new Line());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Line> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Line() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Line(Line other) : this() {
    lsid_ = other.lsid_;
    on_ = other.on_;
    min_ = other.min_;
    max_ = other.max_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Line Clone() {
    return new Line(this);
  }

  /// <summary>Field number for the "lsid" field.</summary>
  public const int LsidFieldNumber = 1;
  private int lsid_;
  /// <summary>
  ///区服id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Lsid {
    get { return lsid_; }
    set {
      lsid_ = value;
    }
  }

  /// <summary>Field number for the "on" field.</summary>
  public const int OnFieldNumber = 2;
  private bool on_;
  /// <summary>
  ///是否开启排队功能
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool On {
    get { return on_; }
    set {
      on_ = value;
    }
  }

  /// <summary>Field number for the "min" field.</summary>
  public const int MinFieldNumber = 3;
  private int min_;
  /// <summary>
  ///排队最少等待时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Min {
    get { return min_; }
    set {
      min_ = value;
    }
  }

  /// <summary>Field number for the "max" field.</summary>
  public const int MaxFieldNumber = 4;
  private int max_;
  /// <summary>
  ///排队最多等待时间
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Max {
    get { return max_; }
    set {
      max_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Line);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Line other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Lsid != other.Lsid) return false;
    if (On != other.On) return false;
    if (Min != other.Min) return false;
    if (Max != other.Max) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Lsid != 0) hash ^= Lsid.GetHashCode();
    if (On != false) hash ^= On.GetHashCode();
    if (Min != 0) hash ^= Min.GetHashCode();
    if (Max != 0) hash ^= Max.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Lsid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Lsid);
    }
    if (On != false) {
      output.WriteRawTag(16);
      output.WriteBool(On);
    }
    if (Min != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Min);
    }
    if (Max != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Max);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Lsid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Lsid);
    }
    if (On != false) {
      output.WriteRawTag(16);
      output.WriteBool(On);
    }
    if (Min != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Min);
    }
    if (Max != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Max);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Lsid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lsid);
    }
    if (On != false) {
      size += 1 + 1;
    }
    if (Min != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Min);
    }
    if (Max != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Max);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Line other) {
    if (other == null) {
      return;
    }
    if (other.Lsid != 0) {
      Lsid = other.Lsid;
    }
    if (other.On != false) {
      On = other.On;
    }
    if (other.Min != 0) {
      Min = other.Min;
    }
    if (other.Max != 0) {
      Max = other.Max;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Lsid = input.ReadInt32();
          break;
        }
        case 16: {
          On = input.ReadBool();
          break;
        }
        case 24: {
          Min = input.ReadInt32();
          break;
        }
        case 32: {
          Max = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Lsid = input.ReadInt32();
          break;
        }
        case 16: {
          On = input.ReadBool();
          break;
        }
        case 24: {
          Min = input.ReadInt32();
          break;
        }
        case 32: {
          Max = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class OnlineTime : pb::IMessage<OnlineTime>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<OnlineTime> _parser = new pb::MessageParser<OnlineTime>(() => new OnlineTime());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<OnlineTime> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public OnlineTime() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public OnlineTime(OnlineTime other) : this() {
    date_ = other.date_;
    duration_ = other.duration_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public OnlineTime Clone() {
    return new OnlineTime(this);
  }

  /// <summary>Field number for the "date" field.</summary>
  public const int DateFieldNumber = 1;
  private string date_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Date {
    get { return date_; }
    set {
      date_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "duration" field.</summary>
  public const int DurationFieldNumber = 2;
  private long duration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Duration {
    get { return duration_; }
    set {
      duration_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as OnlineTime);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(OnlineTime other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Date != other.Date) return false;
    if (Duration != other.Duration) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Date.Length != 0) hash ^= Date.GetHashCode();
    if (Duration != 0L) hash ^= Duration.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Date.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Date);
    }
    if (Duration != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Duration);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Date.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Date);
    }
    if (Duration != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Duration);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Date.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Date);
    }
    if (Duration != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Duration);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(OnlineTime other) {
    if (other == null) {
      return;
    }
    if (other.Date.Length != 0) {
      Date = other.Date;
    }
    if (other.Duration != 0L) {
      Duration = other.Duration;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Date = input.ReadString();
          break;
        }
        case 16: {
          Duration = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Date = input.ReadString();
          break;
        }
        case 16: {
          Duration = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class UIDInfo : pb::IMessage<UIDInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UIDInfo> _parser = new pb::MessageParser<UIDInfo>(() => new UIDInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UIDInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AuthReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UIDInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UIDInfo(UIDInfo other) : this() {
    uid_ = other.uid_;
    realNameSign_ = other.realNameSign_;
    id_ = other.id_;
    onlineTimeData_ = other.onlineTimeData_.Clone();
    authCount_ = other.authCount_;
    authTime_ = other.authTime_;
    totalOnlineTime_ = other.totalOnlineTime_;
    rncStatus_ = other.rncStatus_;
    totalFailCount_ = other.totalFailCount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UIDInfo Clone() {
    return new UIDInfo(this);
  }

  /// <summary>Field number for the "uid" field.</summary>
  public const int UidFieldNumber = 1;
  private string uid_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Uid {
    get { return uid_; }
    set {
      uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "realNameSign" field.</summary>
  public const int RealNameSignFieldNumber = 2;
  private int realNameSign_;
  /// <summary>
  /// 0: 未认证, 1: 未成年, 2: adult
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RealNameSign {
    get { return realNameSign_; }
    set {
      realNameSign_ = value;
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 3;
  private string id_ = "";
  /// <summary>
  /// 身份证号
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "onlineTimeData" field.</summary>
  public const int OnlineTimeDataFieldNumber = 4;
  private static readonly pb::FieldCodec<global::OnlineTime> _repeated_onlineTimeData_codec
      = pb::FieldCodec.ForMessage(34, global::OnlineTime.Parser);
  private readonly pbc::RepeatedField<global::OnlineTime> onlineTimeData_ = new pbc::RepeatedField<global::OnlineTime>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::OnlineTime> OnlineTimeData {
    get { return onlineTimeData_; }
  }

  /// <summary>Field number for the "authCount" field.</summary>
  public const int AuthCountFieldNumber = 5;
  private int authCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AuthCount {
    get { return authCount_; }
    set {
      authCount_ = value;
    }
  }

  /// <summary>Field number for the "authTime" field.</summary>
  public const int AuthTimeFieldNumber = 6;
  private long authTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long AuthTime {
    get { return authTime_; }
    set {
      authTime_ = value;
    }
  }

  /// <summary>Field number for the "totalOnlineTime" field.</summary>
  public const int TotalOnlineTimeFieldNumber = 7;
  private long totalOnlineTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long TotalOnlineTime {
    get { return totalOnlineTime_; }
    set {
      totalOnlineTime_ = value;
    }
  }

  /// <summary>Field number for the "rncStatus" field.</summary>
  public const int RncStatusFieldNumber = 8;
  private int rncStatus_;
  /// <summary>
  /// 认证状态 0:认证成功 1:认证中 2:认证失败 3:待认证
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RncStatus {
    get { return rncStatus_; }
    set {
      rncStatus_ = value;
    }
  }

  /// <summary>Field number for the "totalFailCount" field.</summary>
  public const int TotalFailCountFieldNumber = 9;
  private int totalFailCount_;
  /// <summary>
  /// 总失败次数
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TotalFailCount {
    get { return totalFailCount_; }
    set {
      totalFailCount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UIDInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UIDInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Uid != other.Uid) return false;
    if (RealNameSign != other.RealNameSign) return false;
    if (Id != other.Id) return false;
    if(!onlineTimeData_.Equals(other.onlineTimeData_)) return false;
    if (AuthCount != other.AuthCount) return false;
    if (AuthTime != other.AuthTime) return false;
    if (TotalOnlineTime != other.TotalOnlineTime) return false;
    if (RncStatus != other.RncStatus) return false;
    if (TotalFailCount != other.TotalFailCount) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Uid.Length != 0) hash ^= Uid.GetHashCode();
    if (RealNameSign != 0) hash ^= RealNameSign.GetHashCode();
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    hash ^= onlineTimeData_.GetHashCode();
    if (AuthCount != 0) hash ^= AuthCount.GetHashCode();
    if (AuthTime != 0L) hash ^= AuthTime.GetHashCode();
    if (TotalOnlineTime != 0L) hash ^= TotalOnlineTime.GetHashCode();
    if (RncStatus != 0) hash ^= RncStatus.GetHashCode();
    if (TotalFailCount != 0) hash ^= TotalFailCount.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Uid.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Uid);
    }
    if (RealNameSign != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(RealNameSign);
    }
    if (Id.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Id);
    }
    onlineTimeData_.WriteTo(output, _repeated_onlineTimeData_codec);
    if (AuthCount != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(AuthCount);
    }
    if (AuthTime != 0L) {
      output.WriteRawTag(48);
      output.WriteInt64(AuthTime);
    }
    if (TotalOnlineTime != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(TotalOnlineTime);
    }
    if (RncStatus != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(RncStatus);
    }
    if (TotalFailCount != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(TotalFailCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Uid.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Uid);
    }
    if (RealNameSign != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(RealNameSign);
    }
    if (Id.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Id);
    }
    onlineTimeData_.WriteTo(ref output, _repeated_onlineTimeData_codec);
    if (AuthCount != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(AuthCount);
    }
    if (AuthTime != 0L) {
      output.WriteRawTag(48);
      output.WriteInt64(AuthTime);
    }
    if (TotalOnlineTime != 0L) {
      output.WriteRawTag(56);
      output.WriteInt64(TotalOnlineTime);
    }
    if (RncStatus != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(RncStatus);
    }
    if (TotalFailCount != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(TotalFailCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Uid.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
    }
    if (RealNameSign != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RealNameSign);
    }
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    size += onlineTimeData_.CalculateSize(_repeated_onlineTimeData_codec);
    if (AuthCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(AuthCount);
    }
    if (AuthTime != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(AuthTime);
    }
    if (TotalOnlineTime != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalOnlineTime);
    }
    if (RncStatus != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RncStatus);
    }
    if (TotalFailCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalFailCount);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UIDInfo other) {
    if (other == null) {
      return;
    }
    if (other.Uid.Length != 0) {
      Uid = other.Uid;
    }
    if (other.RealNameSign != 0) {
      RealNameSign = other.RealNameSign;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    onlineTimeData_.Add(other.onlineTimeData_);
    if (other.AuthCount != 0) {
      AuthCount = other.AuthCount;
    }
    if (other.AuthTime != 0L) {
      AuthTime = other.AuthTime;
    }
    if (other.TotalOnlineTime != 0L) {
      TotalOnlineTime = other.TotalOnlineTime;
    }
    if (other.RncStatus != 0) {
      RncStatus = other.RncStatus;
    }
    if (other.TotalFailCount != 0) {
      TotalFailCount = other.TotalFailCount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Uid = input.ReadString();
          break;
        }
        case 16: {
          RealNameSign = input.ReadInt32();
          break;
        }
        case 26: {
          Id = input.ReadString();
          break;
        }
        case 34: {
          onlineTimeData_.AddEntriesFrom(input, _repeated_onlineTimeData_codec);
          break;
        }
        case 40: {
          AuthCount = input.ReadInt32();
          break;
        }
        case 48: {
          AuthTime = input.ReadInt64();
          break;
        }
        case 56: {
          TotalOnlineTime = input.ReadInt64();
          break;
        }
        case 64: {
          RncStatus = input.ReadInt32();
          break;
        }
        case 72: {
          TotalFailCount = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Uid = input.ReadString();
          break;
        }
        case 16: {
          RealNameSign = input.ReadInt32();
          break;
        }
        case 26: {
          Id = input.ReadString();
          break;
        }
        case 34: {
          onlineTimeData_.AddEntriesFrom(ref input, _repeated_onlineTimeData_codec);
          break;
        }
        case 40: {
          AuthCount = input.ReadInt32();
          break;
        }
        case 48: {
          AuthTime = input.ReadInt64();
          break;
        }
        case 56: {
          TotalOnlineTime = input.ReadInt64();
          break;
        }
        case 64: {
          RncStatus = input.ReadInt32();
          break;
        }
        case 72: {
          TotalFailCount = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
